# Generated by Django 5.1.4 on 2024-12-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airfryer_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients1",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients10",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients2",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients3",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients4",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients5",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients6",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients7",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients8",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients9",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions1",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions10",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions2",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions3",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions4",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions5",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions6",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions7",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions8",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions9",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="time",
            field=models.IntegerField(null=True),
        ),
    ]
