# Generated by Django 5.1.4 on 2024-12-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "airfryer_app",
            "0002_remove_recipe_ingredients_remove_recipe_instructions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients10",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients6",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients7",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients8",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients9",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions10",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions6",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions7",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions8",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions9",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients1",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients2",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients3",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients4",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients5",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions1",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions2",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions3",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions4",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions5",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
