# Generated by Django 5.1.4 on 2024-12-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airfryer_app", "0005_alter_recipe_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients1",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients2",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients3",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients4",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients5",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions1",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions2",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions3",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions4",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions5",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
