# Generated by Django 5.1.4 on 2024-12-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airfryer_app", "0010_recipe_user_alter_recipe_description_and_more"),
    ]

    operations = []
